# What is PyTorch

In [1]:
from __future__ import print_function
import torch

In [27]:
x = torch.Tensor(5, 3)
print(x)


 0.0000e+00 -1.5846e+29  2.0426e+11
 2.8671e-42  2.7156e-32  1.4013e-45
 0.0000e+00  0.0000e+00  0.0000e+00
 0.0000e+00  0.0000e+00  0.0000e+00
 0.0000e+00 -1.5846e+29  0.0000e+00
[torch.FloatTensor of size 5x3]



In [30]:
x = torch.rand(5, 3)
print(x)


 0.5710  0.9631  0.8559
 0.5843  0.4122  0.7544
 0.1771  0.1617  0.7007
 0.4084  0.7395  0.2431
 0.1145  0.8969  0.1369
[torch.FloatTensor of size 5x3]



In [29]:
print(x.size())

torch.Size([5, 3])


In [7]:
import numpy as np

In [16]:
y = np.array((5, 3), dtype=np.int32)

In [17]:
print(y)

[5 3]


In [18]:
y.shape

(2,)

In [31]:
y = np.zeros((3, 5))

In [32]:
print(y)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
